stages:
  trainme:
    cmd: python train.py
    deps:
      - users.csv
    params:
      params.yaml:
        models.dense: 512
        models.epochs: 10
        models.log_file: plots.csv
    outs:
      - logs
    metrics:
    - summary.json:
        cache: false
    plots:
    - plots.csv:
        cache: false
        y: accuracy
        x_label: Epoch
        title: Accuracy
