stages:
  trainme:
    cmd: python train.py
    deps:
      - users.csv
    params:
      - models.dense
      - models.epochs
      - models.log_file
    outs:
      - logs
    metrics:
    - summary.json:
        cache: false
    plots:
    - plots.csv:
        cache: false
        y: accuracy
        x_label: Epoch
        title: Accuracy
